import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-dim": "#eb0000",
        "on-tertiary": "#53157a",
        "surface-container-highest": "#262626",
        "on-surface-variant": "#ababab",
        "tertiary-fixed-dim": "#c889f1",
        secondary: "#e2e2e2",
        "on-primary-fixed-variant": "#600000",
        primary: "#ff8e7d",
        "inverse-on-surface": "#555555",
        outline: "#757575",
        "surface-container-lowest": "#000000",
        "on-tertiary-fixed-variant": "#56197d",
        "on-secondary-container": "#d0d0d0",
        "secondary-fixed-dim": "#d4d4d4",
        "on-tertiary-container": "#47026f",
        "inverse-primary": "#c10100",
        background: "#0e0e0e",
        "surface-container-low": "#131313",
        "on-background": "#ffffff",
        "surface-container-high": "#1f1f1f",
        "surface-dim": "#0e0e0e",
        "on-primary-container": "#4f0000",
        "tertiary-dim": "#c384eb",
        "on-primary": "#650000",
        error: "#ff6e84",
        "surface-container": "#191919",
        "tertiary-fixed": "#d697ff",
        "inverse-surface": "#f9f9f9",
        "secondary-container": "#454747",
        "error-dim": "#d73357",
        "on-error-container": "#ffb2b9",
        "surface-tint": "#ff8e7d",
        "primary-fixed": "#ff7763",
        "outline-variant": "#484848",
        tertiary: "#dba2ff",
        "on-surface": "#ffffff",
        "on-tertiary-fixed": "#2a0044",
        "on-error": "#490013",
        "tertiary-container": "#d191fa",
        "on-primary-fixed": "#000000",
        "secondary-dim": "#d4d4d4",
        "on-secondary-fixed-variant": "#5a5c5c",
        "on-secondary": "#505252",
        "primary-container": "#ff7763",
        surface: "#0e0e0e",
        "secondary-fixed": "#e2e2e2",
        "primary-fixed-dim": "#ff5b47",
        "on-secondary-fixed": "#3e4040",
        "surface-variant": "#262626",
        "error-container": "#a70138",
        "surface-bright": "#2c2c2c",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        quote: ["Cormorant Garamond", "serif"],
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      keyframes: {
        "fade-up": {
          "0%": { opacity: "0", transform: "translateY(30px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "slide-in-right": {
          "0%": { opacity: "0", transform: "translateX(40px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        "scan": {
          "0%": { transform: "translateY(-100%)" },
          "100%": { transform: "translateY(100vh)" },
        },
        "pulse-glow": {
          "0%, 100%": { boxShadow: "0 0 10px rgba(235,0,0,0.3)" },
          "50%": { boxShadow: "0 0 30px rgba(235,0,0,0.7)" },
        },
        "flicker": {
          "0%, 100%": { opacity: "1" },
          "92%": { opacity: "1" },
          "93%": { opacity: "0.4" },
          "94%": { opacity: "1" },
          "96%": { opacity: "0.6" },
          "97%": { opacity: "1" },
        },
        "counter": {
          from: { opacity: "0", transform: "translateY(10px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "bar-fill": {
          "0%": { width: "0%" },
          "100%": { width: "84%" },
        },
      },
      animation: {
        "fade-up": "fade-up 0.8s ease forwards",
        "fade-in": "fade-in 0.6s ease forwards",
        "slide-in-right": "slide-in-right 0.8s ease forwards",
        "scan": "scan 4s linear infinite",
        "pulse-glow": "pulse-glow 2s ease-in-out infinite",
        "flicker": "flicker 5s infinite",
        "bar-fill": "bar-fill 1.2s ease-out forwards",
      },
    },
  },
  plugins: [],
};
export default config;
